# Jekyll
server: true
auto: true
markdown: rdiscount
pygments: true
permalink: /:title.html

# Conference info
conf:
  name: "d3.unconf"
  description: "d3.unconf is a one-day gathering of data visualization practitioners."
  date: "March 29, 2014"
  price: "$100"
  address: "GitHub HQ, 88 Colin P Kelly Jr St, San Francisco, CA 94107"
  venue: "GitHub HQ"
  city: "San Francisco"

# Site info
site:
  url: "http://visfest.com/d3unconf"
  favicon: "/img/favicon.ico"
  googleanalytics: "UA-46805120-1"
  images:
    cover: "/img/IMG_1383.jpg"
    facebook: "http://visfest.com/img/facebook_og.png"

# Active sections on the website
sections:
  about: true
  mailing_list: true
  location: true
  faq: true
  speakers: true
  schedule: true
  sponsors: true
  partners: true
  contact: false
  code_of_conduct: true 
  on_sale_now: true

# The entire schedule
schedule:
  -
    name: "Breakfast"
    time: "9:00 AM"
    global: true
  -
    name: "Session Planning"
    time: "9:30 AM"
    global: true
  -
    name: "Irene Ros"
    photo: "/img/keynote.jpg"
    bio: '<a href="https://twitter.com/ireneros">Irene</a> is a core developer for <a href="http://misoproject.com/">The Miso Project</a>, a framework for interactive storytelling with data. She organizes the Boston conference <a href="http://openvisconf.com/">OpenVisConf</a> and is a Senior Developer at <a href="http://bocoup.com/">Bocoup.</a>'
    company: "Boucoup"
    twitter: "ireneros"
    presentation:
      title: "Opening Keynote"
      time: "10:00 AM"
    global: true
  - 
    time: "10:30 AM"
    sessions:
    - "Session 1A"
    - "Session 1B"
    - "Session 1C"
    - "Session 1D"
    - "Session 1E"
  - 
    time: "11:30 AM"
    sessions:
    - "Session 2A"
    - "Session 2B"
    - "Session 2C"
    - "Session 2D"
    - "Session 2E"
  -
    name: "Lunch"
    time: "12:30 PM"
    global: true
  - 
    time: "1:30 PM"
    sessions:
    - "Session 3A"
    - "Session 3B"
    - "Session 3C"
    - "Session 3D"
    - "Session 3E"
  - 
    time: "2:30 PM"
    sessions:
    - "Session 4A"
    - "Session 4B"
    - "Session 4C"
    - "Session 4D"
    - "Session 4E"
  -
    name: "Coffee Break"
    time: "3:30 PM"
    global: true
  - 
    time: "4:00 PM"
    sessions:
    - "Session 4A"
    - "Session 4B"
    - "Session 4C"
    - "Session 4D"
    - "Session 4E"
  - 
    time: "5:00 PM"
    sessions:
    - "Session 4A"
    - "Session 4B"
    - "Session 4C"
    - "Session 4D"
    - "Session 4E"
  -
    name: "Dinner"
    time: "6:00 PM"
    global: true
  -
    name: "Github Pub!"
    time: "7:00 PM"
    global: true

# List of Partners
partners:
  -
    name: "Bay Area d3 Meetup"
    logo: "/img/d3bayarea.png"
    url: "http://www.meetup.com/Bay-Area-d3-User-Group"

sponsors:
  -
    name: "GitHub"
